//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanQuanAo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseBanQuanAoEntities : DbContext
    {
        public DatabaseBanQuanAoEntities()
            : base("name=DatabaseBanQuanAoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTDatHang> CTDatHangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbDanhMuc> tbDanhMucs { get; set; }
        public virtual DbSet<tbNguoiDung> tbNguoiDungs { get; set; }
        public virtual DbSet<tbSanPham> tbSanPhams { get; set; }
        public virtual DbSet<ThongTinThanhToan> ThongTinThanhToans { get; set; }
    }
}
