//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNguoiDung
    {
        public int MaNguoiDung { get; set; }
        public string TaiKhoanNguoiDung { get; set; }
        public string MatKhauNguoiDung { get; set; }
        public string TenNguoiDung { get; set; }
        public string DiaChiNguoiDung { get; set; }
        public Nullable<int> SDTNguoiDung { get; set; }
        public string GioiTinhNguoiDung { get; set; }
    }
}
